---
queue_rules:
  - name: default
    conditions:
      - "check-success=Build Deb Package"

pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "check-success=Build Deb Package"
    actions:
      queue:
        method: rebase
        name: default
