---
queue_rules:
  - name: default
    conditions:
      - "check-success=Build and Test"

pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "check-success=Build and Test"
    actions:
      queue:
        method: rebase
        name: default
