[package]
name = "modem-keepaliver"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.51"
clap = { version = "3.0.13", features = ["derive"] }
log = "0.4.14"
num-derive = "0.3.3"
num-traits = "0.2.14"
simplelog = "0.11.1"
tokio = { version = "1.16.1", features = ["rt-multi-thread","time","macros"] }
zbus = "2.0.1"

[profile.release]
opt-level="s"
lto="fat"
