[package]
name = "modem-keepaliver"
version = "0.2.1"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.3.24", features = ["derive"] }
log = "0.4.20"
num-derive = "0.4.0"
num-traits = "0.2.16"
simplelog = "0.12.1"
tokio = { version = "1.32.0", features = ["rt-multi-thread","time","macros"] }
zbus = "3.14.1"

[profile.release]
opt-level="s"
lto="fat"
