[package]
name = "modem-keepaliver"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.62"
clap = { version = "3.2.17", features = ["derive"] }
log = "0.4.17"
num-derive = "0.3.3"
num-traits = "0.2.15"
simplelog = "0.12.0"
tokio = { version = "1.20.1", features = ["rt-multi-thread","time","macros"] }
zbus = "2.3.2"

[profile.release]
opt-level="s"
lto="fat"
