[package]
name = "modem-keepaliver"
version = "0.2.1"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.28", features = ["derive"] }
log = "0.4.17"
num-derive = "0.3.3"
num-traits = "0.2.15"
simplelog = "0.12.0"
tokio = { version = "1.22.0", features = ["rt-multi-thread","time","macros"] }
zbus = "3.5.0"

[profile.release]
opt-level="s"
lto="fat"
