[package]
name = "modem-keepaliver"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.51"
dbus = "0.9.5"
dbus-tokio = "0.7.5"
env_logger = "0.9.0"
log = "0.4.14"
num-derive = "0.3.3"
num-traits = "0.2.14"
tokio = { version = "1.14.0", features = ["full"] }
