[package]
name = "modem-keepaliver"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.51"
clap = { version = "3.0.0-rc.9", features = ["derive"] }
log = "0.4.14"
num-derive = "0.3.3"
num-traits = "0.2.14"
simplelog = "0.11.1"
tokio = { version = "1.14.0", features = ["rt-multi-thread","time","macros"] }
zbus = "1.9.2"