[package]
name = "modem-keepaliver"
version = "0.2.1"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.2.7", features = ["derive"] }
log = "0.4.17"
num-derive = "0.3.3"
num-traits = "0.2.15"
simplelog = "0.12.1"
tokio = { version = "1.28.1", features = ["rt-multi-thread","time","macros"] }
zbus = "3.12.0"

[profile.release]
opt-level="s"
lto="fat"
